<img src = "https://numpy.org/images/logo.svg" width="300"/>


# Computación numérica con *Numpy*

[*NumPy*](https://numpy.org) es un paquete de Python para computación científica. Es una biblioteca de Python que proporciona objetos de matriz multidimensional, objetos derivados como matrices enmascaradas, y una variedad de rutinas para operaciones rápidas en matrices que incluyen manipulación matemática, lógica, de formas, clasificación, selección, transformadas, álgebra lineal, operaciones estadísticas, simulación aleatoria y mucho más.

## Arrays

Un **array** es la estructura de datos central del paquete *NumPy*, es un arreglo ordenado de elementos del mismo tipo, diferente a la lista tradicional de Python que puede contener distintos tipos de datos. La ventaja del **array** sobre una lista radica en que se le puede aplicar una gran variedad de operadores matemáticos que no pueden ser normalmente usados en listas. Por ejemplo, un **array** se puede multiplicar por un escalar mientras que las listas no. Los arrays pueden ser creados a partir de una lista y son computacionalmente más eficientes y compactos que las listas, requieren menos espacio de almacenamiento.
<img src = "https://numpy.org/doc/stable/_images/np_array.png" width="720"/>

In [1]:
import numpy as np

v = np.array([1,2,3])
v

array([1, 2, 3])

### ¿Cuales son los atributos de un Array?

El rango (<font color = red>rank</font>) de un **array** es su número de dimensiones, mientras que su forma (<font color = red>shape</font>) será una tupla de enteros con el tamaño del array en cada dimensión. En *NumPy* las dimensiones son llamadas ejes (<font color = red>axes</font>).

In [2]:
m = np.array([[1,2],[3,4],[5,6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

En este caso el primer eje de ```m``` tiene un tamaño de 3, mientras que su segundeo eje tiene un tamaño de 4. Para acceder a esta información se emplean los atributos: ```ndim```(rango), ```shape```(dimensiones) y ```size```(cantidad de elementos).
<img src = "https://numpy.org/doc/stable/_images/np_create_matrix.png" width="720"/>

In [3]:
print("El array m tiene",m.ndim,"ejes, este array es una matriz de dimensión",m.shape,"y contiene",m.size,"elementos.")

El array m tiene 2 ejes, este array es una matriz de dimensión (3, 2) y contiene 6 elementos.


A veces los **arrays** son llamados "ndarray", esto es la abreviatura de "N-dimensional array", lo cual es simplemente un array de cualquier número de dimensiones. En otras ocasiones serán referidos como **1-D array** o array de una dimensión, **2-D array** o array de dos dimensiones, etc. Un **vector** es un array de una única dimensión (no hay distinción entre columnas y filas) mientras que una **matriz** refiere a un array de dos dimensiones. Para arrays con 3 dimensiones o más se suele utilizar el término **tensor**.

### Acceder a los elementos de un array

Los elementos de un **array** son accesibles con los mismos métodos de indexing y slicing de las listas:
<img src = "https://numpy.org/doc/stable/_images/np_indexing.png" width="860"/>

In [4]:
v

array([1, 2, 3])

In [5]:
v[0],v[0:2],v[-2:]

(1, array([1, 2]), array([2, 3]))

### Especificar el tipo de datos de un array

El data type por default de los elementos de un **array** es el de números decimales o floating points (<font color = red>np.float64</font>). Sin embargo, los **arrays** reciben un segundo parametro para especificar el tipo de datos esperado de los elementos, esto puede servir para optimizar la ejecución del código. Para hacerlo se especifíca explícitamente el data type utilizando el parámetro <font color = red>dtype</font>:

In [6]:
np.array([1,2,3,4,5,6], dtype = np.int64)

array([1, 2, 3, 4, 5, 6], dtype=int64)

### Más formas de crear arrays

Se puede crear un array lleno de 0's con la función ```zeros()```:

In [7]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

O un array lleno de 1's con la función ```ones()```:

In [8]:
np.ones([3,4], dtype = np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

Se puede también crear **arrays 1D** con las funciones ```linspace()``` y ```arange()```, ambas funciones reciben 3 parámetros y en ambas los primeros dos son el límite inferior y superior del array respectivamente. La diferencia consiste en que el tercer parámetro de ```linspace()``` especifíca la cantidad de elementos del array y el tercer parámetro de ```arange()``` especifíca la diferencia entre cada elemento del array:

In [9]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
np.arange(0,5,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05, 2.1 , 2.15,
       2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 , 2.65, 2.7 ,
       2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15, 3.2 , 3.25,
       3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 ,
       3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35,
       4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 ,
       4.95])

También se pueden crear **arrays** a partir de datos ya existentes, la función ```concatenate()``` recibe una tupla de arrays que puede concatenar:

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

```concatenate()``` también es aplicable a matrices, el parámetro ```axis``` indica en qué eje se va a concatenar:

In [12]:
x = np.array([[3,1],[4,1]])
y = np.array([[5,9],[2,6]])
print()
print("Si se concatena en el primer eje:\n", np.concatenate((x,y),axis=0) )
print("\nSi se concatena en el segundo eje:\n", np.concatenate((x,y),axis=1) )


Si se concatena en el primer eje:
 [[3 1]
 [4 1]
 [5 9]
 [2 6]]

Si se concatena en el segundo eje:
 [[3 1 5 9]
 [4 1 2 6]]


Si *```x```* y *```y```* tuvieran diferente dimensión, es indispensable especificar el eje en que se va a concatenar y que las dimensiones de la matriz final sean coherentes:

In [13]:
x2 = np.array([[3,1],[4,1]])
y2 = np.array([[5,9]])
np.concatenate((x2,y),axis=0)

array([[3, 1],
       [4, 1],
       [5, 9],
       [2, 6]])

De lo contrario el intérprete retornará el siguiente error:

In [14]:
x2 = np.array([[3,1],[4,1]])
y2 = np.array([[5,9]])
np.concatenate((x2,y2),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Otros métodos para crear **arrays** a partir de otros que ya existan utilizan los métodos de slicing e indexing, por ejemplo:

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
np.array(a[3:8])

array([4, 5, 6, 7, 8])

Este último método también es el más eficiente para eliminar elementos de un **array**. Otra forma de concatenar matrices de igual dimensión menos complicada que la función ```concatenate()```, son las funciones de apilar verticalmente: ```vstack()``` y apilar horizontalmente: ```hstack()```. Esto ayuda a no tener que pensar mucho en el eje de concatenación.

In [16]:
np.vstack((x,y))

array([[3, 1],
       [4, 1],
       [5, 9],
       [2, 6]])

In [17]:
np.hstack((x,y))

array([[3, 1, 5, 9],
       [4, 1, 2, 6]])

También es posible crear múltiples **arrays** de uno solo utilizando las funciones de dividir verticalmente: ```vstack()``` y dividir horizontalmente: ```hstack()```:

In [18]:
M = np.array([[3,1,4,1,5,9,2,6],[5,3,5,8,9,7,9,3],[2,3,8,4,6,2,6,4],[3,3,8,3,2,7,9,5],[0,2,8,8,4,1,9,7]])
M

array([[3, 1, 4, 1, 5, 9, 2, 6],
       [5, 3, 5, 8, 9, 7, 9, 3],
       [2, 3, 8, 4, 6, 2, 6, 4],
       [3, 3, 8, 3, 2, 7, 9, 5],
       [0, 2, 8, 8, 4, 1, 9, 7]])

```M``` se podría separar verticalmente en dos **arrays** del mismo tamaño con:

In [19]:
np.hsplit(M,2)

[array([[3, 1, 4, 1],
        [5, 3, 5, 8],
        [2, 3, 8, 4],
        [3, 3, 8, 3],
        [0, 2, 8, 8]]),
 array([[5, 9, 2, 6],
        [9, 7, 9, 3],
        [6, 2, 6, 4],
        [2, 7, 9, 5],
        [4, 1, 9, 7]])]

O usando una tupla se podría dividir horizontalmente en 3 **arrays** con las posiciones indicadas en la tupla:

In [20]:
np.hsplit(M,(2,6)) # Un array corresponde a los elementos previos a la posición 2, el siguiente a los elementos entre las
                   # posiciones 2 y 6, y el último a los elementos de la posición 6 en adelante.

[array([[3, 1],
        [5, 3],
        [2, 3],
        [3, 3],
        [0, 2]]),
 array([[4, 1, 5, 9],
        [5, 8, 9, 7],
        [8, 4, 6, 2],
        [8, 3, 2, 7],
        [8, 8, 4, 1]]),
 array([[2, 6],
        [9, 3],
        [6, 4],
        [9, 5],
        [9, 7]])]

Estos mismos métodos se pueden aplicar verticalmente:

In [21]:
np.vsplit(M,(2,3))

[array([[3, 1, 4, 1, 5, 9, 2, 6],
        [5, 3, 5, 8, 9, 7, 9, 3]]),
 array([[2, 3, 8, 4, 6, 2, 6, 4]]),
 array([[3, 3, 8, 3, 2, 7, 9, 5],
        [0, 2, 8, 8, 4, 1, 9, 7]])]